title: "Indie Open Source"
description: "free business model resources for independent open source software developers"
url: "https://indieopensource.com"
homepage: "https://indieopensource.com"
repository: "indieopensource/indieopensource.github.io"
repository_url: "https://github.com/indieopensource/indieopensource.github.io"
social_media_image: "https://indieopensource.com/logo-1200.png"
collections:
  indies:
    output: true
  models:
    output: true
  forms:
    output: true
  indie_guides:
    output: true
  user_guides:
    output: true
  contributor_guides:
    output: true
  services:
    output: true
exclude:
- Gemfile
- Gemfile.lock
- README.md
